modLoader="javafml" #mandatory
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/GT-Utility" #optional

[[mods]]
modId="gtcore" #mandatory
version="${version}"
displayName="GT Core" #mandatory
credits="Thanks for this example mod goes to Java"
authors="Trinsdar"
description='''Core Items and blocks used by both gti and gt4r.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gtcore]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtcore]]
    modId="antimatter"
    mandatory=true
    versionRange="[0.2-rc1,)"
    ordering="AFTER"
    side="BOTH"
