modLoader="javafml" #mandatory
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/GT-Utility" #optional

[[mods]]
modId="gtutility" #mandatory
version="${version}"
displayName="GT Utility" #mandatory
credits="Thanks for this example mod goes to Java"
authors="Trinsdar"
description='''Just a simple mod that adds utility blocks from gregtech 5 and 6.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.gtutility]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gtutility]]
    modId="antimatter"
    mandatory=true
    versionRange="[0.2-rc1,)"
    ordering="AFTER"
    side="BOTH"
